### PR TITLE
Add BUIP056 Increase the Block Size Limit at a Support Threshold

### PR DESCRIPTION
**Pull request by tomasvdw**
This PR adds BUIP056 "Increase the Block Size Limit at a Support Threshold" as per recommendation on the forum

### CODE REVIEW

**Comment by sickpig** [comment]
@tomasvdw 
thanks for your PR!

Since the BU member [Zangelbert Bingledack](https://bitco.in/forum/threads/buip056-increase-the-block-size-limit-triggered-by-a-support-threshold.2111/#post-38847)  officially endorsed BUIP 56,  could you please add a `Sponsor` header in the `pre` section indicating Zangelbert as a sponsor of this proposal? 

Please also add the reference to the sponsorship in the README.mediawiki (see: BUIP038 to see how we decide coalesce `Proposer` and ` Sponsor` on the same column)

**Comment by tomasvdw** [comment]
I have added to sponsor to BUIP and the README

**Comment by sickpig** [comment]
@tomasvdw thanks you so much. One last think if you don't mind, could please squash branch commits into a single one? Once you do that I'll merge the PR right away. 

p.s. didn't realize you're the guy behind bicrust til lI saw your avatar on github. Great work!

**Comment by tomasvdw** [comment]
Squashed it.

**Pull request merged**
