### PR TITLE
rename to remove "ua"

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by ftrader** [comment]
I support this.

**Comment by deadalnix** [comment]
Good.

**Comment by sickpig** [comment]
if nobody will object/rise issue I will merge it by te end of te days (CEST time)

**Comment by sickpig** [comment]
@gandrewstone could you rebase please? (simplest way yo resolve conflict and to avoid clutter the git log history due to manual merge)

**Comment by ftrader** [comment]
No need to rebase - has been superceded by PR https://github.com/BitcoinUnlimited/BUIP/pull/46

This one can be closed (abandoned).

**Comment by sickpig** [comment]
superseded by #46 
closing

**Pull request closed without merging**
