### PR TITLE
Residual REQ-3 update after meeting 2017-06-07

### PR DESCRIPTION
**Pull request by ftrader**
As per discussion item no. 2

### CODE REVIEW

**Comment by deadalnix** [comment]
1/ Specifying a upward limit is good, but it needs to be made clear that this is by policy, not consensus.
2/ There needs to be a spec on sigops for the same reason.

**Comment by gandrewstone** [comment]
EB should control the max block I don't see why we need another control.  But I agree with @deadalnix we should mention in the spec that existing BU > 1MB fork rules pertain to this fork.

**Comment by deadalnix** [comment]
@dgenr8 This is a spec for the HF, it'd better spec how the HF consensus rule differs.

**Comment by ftrader** [comment]
I'd like to point out that 'fork block' in this PR (and the spec) refers to the single block > 1MB that triggers the fork, and not all subsequent blocks. Just mentioning it because it is not immediately obvious from the PR title.

I would propose an amendment to specify the sigops rules in a separate PR.

**Comment by ftrader** [comment]
@deadalnix : I'm introducing a sigops definition in https://github.com/BitcoinUnlimited/BUIP/pull/39

Please review - I will refer to these "BU tx/sigops rules" in a further PR to implement your remark 2/ .

@dgenr8 : I believe deadalnix's point is to remind of these already-live rules within the spec so that others can use it to create compatible adaptations of their software. I think that it merits mention with a reference to BUIP040 [1].

[1] https://bitco.in/forum/threads/buip040-passed-emergent-consensus-parameters-and-defaults-for-large-1mb-blocks.1643/

**Comment by sickpig** [comment]
what's the general consensus on this one? do we need other inputs from other parties?

ps this PR is "blocking" #35

**Comment by ftrader** [comment]
I'm ok with not merging this one, as I think @dgenr8 's argument makes sense. There is no need to specially protect the precise fork block if a following block can be large, and I follow @gandrewstone 's view that EB would be sufficient. We might consider changing the default EB to 8MB for the release of this hard fork version?

**Comment by ftrader** [comment]
As discussed on Slack, this will be amended to remove the 8MB constraint on fork block size.
There are some leftovers (modification of the note) that will result in a residual change.
I will amend the title of the PR suitably once the change has been made.

**Comment by ftrader** [comment]
@sickpig : ready for merge once you review and approve.

**Pull request merged**
