### PR TITLE
specify design of BUIP055 config parameters.

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by ftrader** [comment]
I made the initial mistake of including the Design section in the technical spec.

It would probably be better to move this to a client-specific doc/buip-hf-software-design.md or similar file that lives close to the client's documentation and source.

**Comment by sickpig** [comment]
I agree with @ftrader.

**Comment by gandrewstone** [comment]
do you want me to change this PR to create that file?

**Comment by ftrader** [comment]
>do you want me to change this PR to create that file?

@thezerg : that would be great (in the BU repo itself).

Then we could just close this PR as I think the Design subsection has been removed in latest version of spec already.

**Comment by sickpig** [comment]
@gandrewstone don't think this is still relavant. closing. feel free to ping if you think it needs to be reopened.

**Pull request closed without merging**
