### PR TITLE
Add REQ-6-3 : require the use of revised BIP143 transaction digest algorithm for protected transactions

### PR DESCRIPTION
**Pull request by ftrader**
As per 2017-06-07 meeting decision:
Protected transactions (which have bit 6 in hash type set) will be digested using a revised form of the BIP143 transaction hash algorithm.

NOTE:

The link to the revised algorithm needs to be completed, and has been made a TODO in the references.

### CODE REVIEW

**Comment by ftrader** [comment]
Although discussed, this additional requirement needs a bit of review.

**Comment by gandrewstone** [comment]
approved

**Comment by ftrader** [comment]
Added a relative link so that the modified BIP143 hashing spec from https://github.com/deadalnix/BUIP/blob/hashing/BUIP-HF/replay-protected-sighash.md can be dropped into the folder and enable the reference [3].

**Comment by deadalnix** [comment]
Ok made a PR for the doc itself: #49

**Pull request merged**
