### PR TITLE
Remove REQ-6-1 (the OP_RETURN side of the replay protection)

### PR DESCRIPTION
**Pull request by ftrader**

### CODE REVIEW

**Comment by deadalnix** [comment]
This item only help the UASF chain, so there are no reason to include it.

**Comment by dgenr8** [comment]
I'm against this because replay protection helps anyone who wants to control where their tx executes.

Omitting this feature doesn't stop the creation of txes invalid on this chain, but valid on others - it just makes doing it more difficult.

**Comment by gandrewstone** [comment]
I'm against merging this PR.  Let's provide the tools that people need to keep confusion and mistakes to a minimum.  Especially since this tool is relative easy to implement.

**Comment by ftrader** [comment]
Offhand, I think a valid argument could be made that having such OP_RETURN helps the UASF chain  a little (more risk on UASF chain would reduce its value).

But at the same time I would like to support freedom to transact safely. Requiring big-blockers to first separate their coins to be able to safely spend their UASF holdings seems to impose an extra burden on them.

Having an easy way of preventing inclusion on the big-block chain seems more user-friendly and likely to gain support for this fork. So I decided to also oppose merging this and rather keep the OP_RETURN as an option for the user.

**Comment by deadalnix** [comment]
> Having an easy way of preventing inclusion on the big-block chain seems more user-friendly and likely to gain support for this fork

That may be true. One has to talk to exchanges to know. By putting this in up front, however, you lose leverage.

**Comment by deadalnix** [comment]
Also, we we are doing this, this better come with a deactivation builtin, because if not, that's a HF to remove it and we don't want to be stuck with kludge like this forever.

**Comment by ftrader** [comment]
I think a sunset clause is a good idea. I propose to expire this protection 1 year after fork activation.

**Comment by gandrewstone** [comment]
I am "for" the 1 year sunset clause, but make it a block height ~ 1 year after activation because that is simpler than MTP and we don't need to worry about exact timing.

**Comment by dgenr8** [comment]
There is the chance a permanent(?) fork a la ETH/ETC.  Most spends will become fork-specific after a while anyway (as new coins get mixed in) but there will always be a need for control when moving old coins.  Bitcoind, like DNA, already has an ugly record of its past, with the old fork checks.

**Comment by ftrader** [comment]
It was decided to add a sunset clause of ~ 1 year (PR https://github.com/BitcoinUnlimited/BUIP/pull/47 ) instead of removing REQ-6-1 entirely.

Closing this PR .

**Pull request closed without merging**
