### PR TITLE
Remove REQ-5, the re-org protection given by REQ-3 is considered sufficient

### PR DESCRIPTION
**Pull request by ftrader**

### CODE REVIEW

**Comment by deadalnix** [comment]
Good. Simpler is better.

**Comment by dgenr8** [comment]
Agreed

**Comment by gandrewstone** [comment]
I agree, I think that with this in place, an attacker could craft attack blocks that create a permanent partition with 2 forks.

**Comment by ftrader** [comment]
I also support this.

**Comment by sickpig** [comment]
if nobody will object/rise issue I will merge it by the end of the day (CEST time)

**Pull request merged**
